sudo: false
language: go
branches:
  only:
    - master

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

env:
  global:
    - GOARCH=amd64
    - TRAVISTEST=true

go_import_path: gorgonia.org/vecf32

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get -u -v -t .

script:
  - ./test.sh

matrix:
  allow_failures:
    - go: tip
